In [2]:
import pandas as pd
data = {
    'color': ['green', 'yellow', 'red', 'blue', 'white'],
    'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
    'price': [1.2, 1.0, 0.6, 0.9, 1.5]
}

df = pd.DataFrame(data)

In [4]:
df2 = pd.DataFrame(data, columns = ['object','price'])
df2

   object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.5

In [10]:
df2.columns

Index(['object', 'price'], dtype='str')

In [12]:
df2.object
df

    color  object  price
0   green    ball    1.2
1  yellow     pen    1.0
2     red  pencil    0.6
3    blue   paper    0.9
4   white     mug    1.5

In [13]:
df.loc[2:4]

   color  object  price
2    red  pencil    0.6
3   blue   paper    0.9
4  white     mug    1.5

In [16]:
df.loc[[2,4]]

   color  object  price
2    red  pencil    0.6
4  white     mug    1.5

In [17]:
df

    color  object  price
0   green    ball    1.2
1  yellow     pen    1.0
2     red  pencil    0.6
3    blue   paper    0.9
4   white     mug    1.5

In [26]:
df.iloc[2:4, 1:4]

   object  price
2  pencil    0.6
3   paper    0.9

In [24]:
df.loc[2:3, ['object', 'price']]

   object  price
2  pencil    0.6
3   paper    0.9

In [30]:
df.columns.name = 'item '
df.loc[[2,4],['object','price' ]]

item    object  price
index
2       pencil    0.6
4          mug    1.5

In [34]:
df['new'] = 12
df

item     color  object  price  new
index
0        green    ball    1.2   12
1       yellow     pen    1.0   12
2          red  pencil    0.6   12
3         blue   paper    0.9   12
4        white     mug    1.5   12